export const START_SEARCH = 'START_SEARCH';
export const RECIVED_SEARCH_RESULTS = 'RECIVED_SEARCH_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const PLAY_MUSIC = 'PLAY_MUSIC';
export const PAUSE_MUSIC = 'PAUSE_MUSIC';

export const MUSIC_STREAM_RECEIVED = 'MUSIC_STREAM_RECEIVED';
export const REQUEST_MUSIC_STREAM = 'REQUEST_MUSIC_STREAM';
export const REQUEST_MUSIC_STREAM_ERROR = 'REQUEST_MUSIC_STREAM_ERROR';

export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
